export const projectRoles: {
  readonly [key in typeof roles[number]]: readonly typeof projectPrivileges[number][];
} = {
  guest: [],
  basic: ["activate task", "create task", "modify self-created task", "remove self-created task"],
  standard: [
    "activate task",
    "create task",
    "modify self-created task",
    "remove self-created task",
    "modify task",
    "remove task",
    "change tasks order",
  ],
  admin: [
    "activate task",
    "create task",
    "modify self-created task",
    "remove self-created task",
    "modify task",
    "remove task",
    "change tasks order",
    "mark task important",
    "modify important task",
    "remove important task",
    "create task pack",
    "modify task pack",
    "change task packs order",
    "remove task pack",
    "block task packs",
    "block unimportant tasks in task pack",
  ],
  owner: [
    "activate task",
    "create task",
    "modify self-created task",
    "remove self-created task",
    "modify task",
    "remove task",
    "change tasks order",
    "mark task important",
    "modify important task",
    "remove important task",
    "create task pack",
    "modify task pack",
    "change task packs order",
    "remove task pack",
    "block task packs",
    "block unimportant tasks in task pack",
    "task stages",
    "task types",
    "add user",
    "remove user",
    "user role",
    "project title and description",
    "remove project",
  ],
} as const;

export const roles = ["guest", "basic", "standard", "admin", "owner"] as const;

export const projectPrivileges = [
  "activate task",
  "create task",
  "modify self-created task",
  "remove self-created task",
  "modify task",
  "remove task",
  "change tasks order",
  "mark task important",
  "modify important task",
  "remove important task",
  "create task pack",
  "modify task pack",
  "change task packs order",
  "remove task pack",
  "block task packs",
  "block unimportant tasks in task pack",
  "task stages",
  "task types",
  "add user",
  "remove user",
  "user role",
  "project title and description",
  "remove project",
] as const;
