"use client";

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="Cross-Origin-Opener-Policy" content="same-origin-allow-popups"></meta>
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
