name: Development Deployment
on:
  push:
    branches-ignore:
      - main
      - preview
jobs:
  Deploy-Development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Firebase tools
        run: npm install -g firebase-tools
      - name: Instal dependencies
        run: npm ci
      - name: Run local emulator firestore rules tests
        run: firebase emulators:exec "npm run test:firestore_rules" --project normkeeper-dev
      - name: Run local emulator firestore api tests
        run: firebase emulators:exec "npm run test:api" --project normkeeper-dev
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run local emulator Playwright tests
        run: firebase emulators:exec "npm run test:e2e" --project normkeeper-dev
