name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - preview
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Variables
        run: vercel env pull --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Firebase tools
        run: npm install -g firebase-tools
      - name: Instal dependencies
        run: npm ci
      - name: Run local emulator firestore rules tests
        run: firebase emulators:exec "npm run test:firestore_rules" --project ticket-tracker-dev
      - name: Update firestore security rules
        run: node ./utils/deployFirestoreRules.js
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Jest server api tests
        run: npm run server:test:api
      - name: Run Playwright preview server tests
        run: npm run server:preview:test:e2e
